### ISSUE TITLE
Memory leak when required repeatedly

### ISSUE THREAD

**Issue by davidtheclark** [isaacs/node-graceful-fs#102]
(This has been my first effort at debugging a memory leak, so if you have any advice on how I can do this better or be more helpful, please let me know!)

I think I've run into a memory leak in this module. Here's the short backstory: I work on a project, [stylelint](https://github.com/stylelint/stylelint), that has *a lot* of tests. We end up running >20K assertions across hundreds of test files. We've been experimenting with the test runner Jest, but it always crashes on Node 4. I logged heap statistics and with each test file saw the heap growing, with inadequate cleanup, until the crash. Through some trial-and-error experiments, I think I tracked this behavior down to a dependency, [cosmiconfig](https://github.com/davidtheclark/cosmiconfig), that uses *this* module. When I change cosmiconfig's usage of `graceful-fs` to Node's `fs`, stylelint's memory problem goes away: the garbage collection adequately reduces memory usage when the heap has grown too much.

I'm not sure what the next steps would be for diagnosing this, but I can try to help if anybody has any suggestions.

**Comment by mrrinot** [comment]
This is still a problem

**Comment by alexandr2110pro** [comment]
Yeah! This is still a problem.

 @isaacs  can you please respond to people?

**Comment by kirillgroshkov** [comment]
Still a problem for us as well (using Jest and `fs-extra`, which depends on `node-graceful-fs`)

**Comment by kirillgroshkov** [comment]
great work! waiting for it to be released and included in Jest, etc.

**Comment by SimenB** [comment]
It has been released, and is within semver range in jest. So you should be able to upgrade on your side (although a PR to explicitly bump itnin Jest is welcome)

**Comment by malthoff** [comment]
Unfortunately this does not fix the issues. Jest tests, although using graceful.js in version 4.1.15, quit working with memory heap errors. The RAM consumption increases with every new test. Anything one can do to drop graceful.js on PC entirely?
