### ISSUE TITLE
ES2015 exports

### ISSUE THREAD

**Issue by tunnckoCore** [isaacs/node-graceful-fs#103]
For cool tree shaking.

**Comment by isaacs** [comment]
I do not understand what you are suggesting or asking for.

**Comment by tunnckoCore** [comment]
Sorry. It just can be bundled into bundles, because it can detect what is exported. So it is needed some major refactor that can export patched methods using ES2015 modules.

**Comment by isaacs** [comment]
I don't think that there's any way to make this work in any environment other than Node.js, and so bundling is not really a priority.  Perhaps there's a way to tell webpack (or whatever) to omit this module when building your bundle?

> edit: damn.. almost aways i'm thinking for "can't", but write "can" :D :D

Must be your can-do attitude ;P

**Comment by tunnckoCore** [comment]
> Must be your can-do attitude ;P

Haha, i'm kinda think that that is dyslexia ;d

> Perhaps there's a way to tell webpack (or whatever) to omit this module when building your bundle?

Actually, yes it is possible, but... okey make sense.
