### ISSUE TITLE
node-graceful-fs silently fails on windows

### ISSUE THREAD

**Issue by aeneasr** [isaacs/node-graceful-fs#108]
This is an upstream issue of an [upstream issue (node-fs-extra)](https://github.com/jprichardson/node-fs-extra/issues/358) of this [original comment in electron-packager](https://github.com/electron-userland/electron-packager/issues/544#issuecomment-280419995). That escalated quickly (see what I did there?) :D

electron-packager is a cli helper that packages an electron app. It does so by copying a node app (including node_modules) to the temp directory. This step uses `fs.copy` (from node-fs-extra) which silently fails. 

In particular, apparently, at some point it simply stops without throwing an error, nor calling the callback:

```js
fs.copy(opts.dir, appPath, {filter: ignore.userIgnoreFilter(opts), dereference: shouldDeref}, cb)
```

In node-fs-extra, I traced the issue back to this project, because I am 85% confident that the issue arises from calls [like these](https://github.com/jprichardson/node-fs-extra/blob/master/lib/copy/ncp.js#L55-L75) do not result in a callback or quit unexpectedly.

I'd be glad to help you identify root cause of this issue. Note that this *only* happens on windows. On OSX, everything works fine.

**Comment by arekkas** [comment]
The issue does apparently no longer occur on node 7.6.0

**Comment by coreyfarrell** [comment]
Since the last comment indicates this issue was resolved by a node.js update I'm closing. If the issue reappears please open a new issue.
