### ISSUE TITLE
v3.x branch Broken on Node.js master

### ISSUE THREAD

**Issue by MylesBorins** [isaacs/node-graceful-fs#120]
Specifically by https://github.com/nodejs/node/pull/13295

We've had to deprecate `remove vm.runInDebugContext()` due to the api being deprecated in V8

I'm going to dig in and see if I can come up with a patch for the 3.x branch to avoid ecosystem breakages

**Comment by isaacs** [comment]
I'm not super interested in doing work to support graceful-fs@3.  But, if you want to write a patch, I'd be happy to land it and push a 3.x release.  Please do also reach out to authors using it.  (I've already deprecated it, so they're getting nagged as of yesterday.  Should've probably done that a long time ago.)

**Comment by MylesBorins** [comment]
Thanks for the quick response. This ends up breaking vinyl-fs + gulp... you know the drill. I'll see if I can come up with a quick fix, but if not I'll pass the message to the gulp team. Thankfully we have a bunch of runway to sort this out

**Comment by MylesBorins** [comment]
This seems to be inherited from breakages in natives

closing in lieu of https://github.com/isaacs/natives/issues/14
