### ISSUE TITLE
Cannot read property 'prototype' of undefined in graceful-fs.js

### ISSUE THREAD

**Issue by freewind1103** [isaacs/node-graceful-fs#123]
I'm getting the above error when I do just var fs = require ('fs-extra');

Because npm is hanging on to the package fs, so I not install it to project. I only install fs-extra with graceful-fs

Any idea why?

**Comment by dolanmiu** [comment]
https://github.com/isaacs/node-graceful-fs/issues/109#issuecomment-312097690

**Comment by coreyfarrell** [comment]
I believe this is resolved in the latest graceful-fs.
