### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined line 166 using with @google-cloud/storage

### ISSUE THREAD

**Issue by Thomasbehan** [isaacs/node-graceful-fs#126]
![image](https://user-images.githubusercontent.com/8860273/36255556-6a3d1f5a-1247-11e8-930a-dce94ebf8df2.png)

Any help with this issue would be great... is this a bug in the current version of graceful-fs or node maybe?

code where the error is:
`ReadStream.prototype = Object.create(fs$ReadStream.prototype)`

**Comment by rguntha** [comment]
I am having the same issue..
I am trying to use node-svm package. gracefule-fs is a depandancy to that.
Please help.

I am using the 4.1.11 version of graceful-fs.js

**Comment by rguntha** [comment]
I have observed that when I use the graceful-fs in nodeJs it works fine. The fs module required by graceful-js does have the ReadStream function.

But I am facing the issue while building this in ionic environment. In ionic, the fs module contains very few functions. And it's missing the ReadStream function.

**Comment by LarsLiden** [comment]
I'm still running into this issue.

**Comment by sboudouk** [comment]
Same here...

**Comment by coreyfarrell** [comment]
A patch which should fix this was released to 4.2.3 on Oct 23, 2019.  Can anyone confirm they experience this issue in a project where 4.2.3 is the only version of graceful-fs installed?

**Comment by coreyfarrell** [comment]
Closing this issue as I believe it is resolved in the latest version.  Let us know if this is incorrect.
