### ISSUE TITLE
should rename account for 'EBUSY' on Windows?

### ISSUE THREAD

**Issue by conceptualspace** [isaacs/node-graceful-fs#127]
along with EACCESS and EPERM errors, EBUSY can bubble up if a file is temporarily locked in windows (for example during AV scan or Dropbox sync).

[rimraf treats them the same](https://github.com/isaacs/rimraf/issues/86), shouldnt graceful-fs as well?

**Comment by deninzane** [comment]
Unlink

**Comment by isaacs** [comment]
This should be fixed now.
