### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]: The value of "mode" is out of range. Received 33204

### ISSUE THREAD

**Issue by nicolo-ribaudo** [isaacs/node-graceful-fs#129]
```
RangeError [ERR_OUT_OF_RANGE]: The value of "mode" is out of range. Received 33204
    at Object.fs.fchmod (fs.js:1038:11)
    at Object.fchmod (/home/nicolo/Documenti/dev/babel/node_modules/graceful-fs/polyfills.js:237:17)
    at mode (/home/nicolo/Documenti/dev/babel/node_modules/vinyl-fs/lib/file-operations.js:237:10)
    at onStat (/home/nicolo/Documenti/dev/babel/node_modules/vinyl-fs/lib/file-operations.js:227:14)
    at /home/nicolo/Documenti/dev/babel/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:166:5)
```

I get this error when building the Babel repo with gulp.

Node version: 10.1.0
graceful-fs@4.1.11

It works on node 8

**Comment by motss** [comment]
Just to add on the issue. It happens when you're out of luck. It works sometimes for Node 8+

**Comment by nojimage** [comment]
I got the same problem.

In my case, I solved it by resetting the file permissions of the source file to be processed.
(change from `0664` to `0644`

**Comment by Fedeorlandau** [comment]
It's happening on travis CI

**Comment by SamuelNorbury** [comment]
I've had this happen seemingly random inside a docker container running Node v10.2.1 and Node v10.3.0 with npm@6.1.0, gulp@4.0.0, graceful-fs@4.1.2. Occassionally gulp will run.

**Comment by TimvdLippe** [comment]
This should be getting fixed with https://github.com/nodejs/node/issues/20498 and is backported at https://github.com/nodejs/node/pull/20975
