### ISSUE TITLE
v3.0.11 depends on natives 1.1.1 which is incompatible with Node v10

### ISSUE THREAD

**Issue by sharikovvladislav** [isaacs/node-graceful-fs#130]
Hey!

Node v10 has some breaking changes. natives@1.1.3 has needed fix. Is it possible to patch node-graceful-fs, so it will use newer natives package?

**Comment by isaacs** [comment]
No, not likely.  Use graceful-fs v4 or higher.

**Comment by isaacs** [comment]
Oh, there's already a fix.

Ok, just `npm update` in your project.  You'll get the newer natives.  `npm ls natives` to see it.

**Comment by sharikovvladislav** [comment]
So do you plan to never make a patch for 3.x.x? 

I don't use your package explicitly. I have your dependency though karma allure reporter. I assume, It is not good idea to add explicit dependency to my project t.

I will create issue in karma allure reporter then.

**Comment by isaacs** [comment]
Just run `npm audit fix` and it'll update it to a version that doesn't cause a problem.  There's no need to publish a new version of every module that _could_ use the broken version, if they're also able to use the fixed version.

**Comment by sharikovvladislav** [comment]
Hm.... True.

graceful-fs@3.0.11 depends on 

```
  "dependencies": {
    "natives": "^1.1.0"
  },
```

And it does not have package-lock.json file

But after first npm install (when node_modules does not exist) I have this:

```
+-- karma-allure-reporter@1.4.4
| `-- allure-js-commons@1.0.2
|   +-- fs-extra@0.18.4
|   | +-- graceful-fs@3.0.11
|   | | `-- natives@1.1.1
```

Why not latest available version Oo?

I think I don't understand something. Something like how npm resolves deps in such cases....
