### ISSUE TITLE
Possible auto-publish script improvement

### ISSUE THREAD

**Issue by Fishrock123** [isaacs/node-graceful-fs#145]
I noticed you added some "auto publish" scripts in https://github.com/isaacs/node-graceful-fs/commit/e2c4556a148f31d468602af36a3d6b2a525676df, which seems neat.

I think it'd neat if `preversion` were able to be adjusted to do an `npm pack` into a temporary directory and run the tests there.

Something like:
```
"preversion": "mkdir tmp; npm pack && cd tmp && npm it ../graceful-fs*.tgz --force",
```

The npm cli doesn't like that much though, lol. Maybe this needs some upstreaming to npm to work better for this, or a module to run a slightly more complex set of commands. thoughts?

**Comment by isaacs** [comment]
That wouldn't work unless tests are included in the tarball.

This is the same set of autopublish scripts I put in all the modules I maintain.

It'd be nice if there were a way to tell the module loader to fail to load any files outside of `test/` that won't be included in the package.  Would've prevented that missing file fiasco with 0.4.12.  Tink may be able to deliver this someday.
