### ISSUE TITLE
Change of node engine min version

### ISSUE THREAD

**Issue by dustin-H** [isaacs/node-graceful-fs#146]
Hi there,

I've noticed you just changed the minimal node-version between `0.4.11` and `0.4.12`.

package.json in `0.4.11`:
```
...
"engines": {
    "node": ">=0.4.0"
  },
...
```

package.json in `0.4.12`:
```
...
"engines": {
    "node": ">=6"
  },
...
```

This breaks my build and I think the build of some others.

Could you please change it back, and release this major change as major release?
https://docs.npmjs.com/getting-started/semantic-versioning

Cheers, Dustin

**Comment by isaacs** [comment]
Why does that break your build?  Engines version has been informational for years.  Are you setting `engines-strict=true` in your npm config?

**Comment by dustin-H** [comment]
We've got a build for nodev4 and nodev5. It passed before, however with this change it doesn't:

https://travis-ci.org/minio/minio-js/jobs/450143861#L502

**Comment by isaacs** [comment]
https://github.com/isaacs/node-graceful-fs/issues/141#issuecomment-435709784
