### ISSUE TITLE
Can I use it with memory-fs or WebSocket-fs? Because many times, fs only represents this machine.

### ISSUE THREAD

**Issue by yuchonghua** [isaacs/node-graceful-fs#154]
Can I use it with [memory-fs](https://www.npmjs.com/package/memory-fs) or WebSocket-fs? Because many times, fs only represents this machine, expecting to pass in fs

**Comment by coreyfarrell** [comment]
In theory you could `require('graceful-fs').gracefulify(memoryFS)` to globally patch that module but this is not supported.  This module is designed for the Node.js `fs` module.
