### ISSUE TITLE
require is not a function

### ISSUE THREAD

**Issue by ekkis** [isaacs/node-graceful-fs#156]
graceful-fs is required by `fstream`, which is required by `unzip` (which I use), and it requires `natives`, about which the author states in https://github.com/addaleax/natives "Don't use unless you know what you're doing, or at least, are ok with the risks. Don't say I didn't warn you."

in any case, on OSX 10.14.3 `natives` breaks with the following error:
```
/node_modules/natives/index.js:45
    whitelist.forEach(function (id) {
^
TypeError: require is not a function
    at /node_modules/natives/index.js:50:1
    at Array.forEach (<anonymous>)
    at Object.req [as require] (/node_modules/natives/index.js:45:1)
    at Object.8956 (/node_modules/graceful-fs/fs.js:1:1)
    at __webpack_require__ (/webpack:bootstrap:19:1)
    at Object.2242 (/node_modules/graceful-fs/graceful-fs.js:3:1)
    at __webpack_require__ (/webpack:bootstrap:19:1)
    at Object.7402 (/node_modules/fstream/lib/reader.js:4:1)
    at __webpack_require__ (/webpack:bootstrap:19:1)
    at Object.7821 (/node_modules/fstream/fstream.js:2:1)
```

I don't know why `require` wouldn't be available within NodeJs, nor why graceful-fs would chose to use a module whose author explicitly states:

> When your program is broken by changes to Node's internals, or when Node changes in such a way that this module becomes fundamentally broken, you will likely get little sympathy. Many people in the Node community consider this sort of behavior to be unwise and unseemly, if not outright hostile and morally wrong.

but there it is.  it's broken and it needs to be fixed.  if there isn't an excellent reason to use graceful-fs, it should be yanked from the dependency list.  if there is, someone needs to figure out why it's broken

if I can help in any way please let me know

**Comment by coreyfarrell** [comment]
graceful-fs does not use `natives` directly or indirectly.  See the following code:
```js
gfs.readdir('some-directory', (err, files) => {
  if (err) throw err
  // call something in natives from here.
})
```

In that case graceful-fs would appear in the backtrace but is not responsible for the call to natives, the caller of `gfs.readdir` is responsible.

**Comment by coreyfarrell** [comment]
I just looked at the dependencies again, it appears that `fstream@1.0.8` and above use graceful-fs 4.x, older versions use graceful-fs 3.  Unfortunately the `unzip` module is locked to fstream `>= 0.1.30 < 1` so that module needs to be updated.

I'm closing this issue as it is resolved in current versions of graceful-fs.
