### ISSUE TITLE
fs.stat() with options doesn't work

### ISSUE THREAD

**Issue by manidlou** [isaacs/node-graceful-fs#158]
`fs.stat()` and its relatives accept an additional options object `fs.stat(path[, options], callback)` since node v10.5.0.

https://nodejs.org/api/fs.html#fs_fs_stat_path_options_callback

seems like `graceful-fs` hasn't been updated yet! This will cause issues for projects that depend on `graceful-fs`. I am one of the maintainers of [fs-extra](https://github.com/jprichardson/node-fs-extra) and this prevents us from using `fs.stat()` with `bigint` option!

**Comment by brodybits** [comment]
I think this would need minor code fixes in the following places:

- https://github.com/isaacs/node-graceful-fs/blob/9b47ebe99f25a012e59bb731186b18f73e77ea8a/polyfills.js#L280-L281
- https://github.com/isaacs/node-graceful-fs/blob/9b47ebe99f25a012e59bb731186b18f73e77ea8a/polyfills.js#L294-L295

I suspect the harder part would be to update the tests [`test/stats.js`](https://github.com/isaacs/node-graceful-fs/blob/master/test/stats.js), which seems to only test `statSync`.

**Comment by wmertens** [comment]
same for readdir btw…

**Comment by JustinLivi** [comment]
I opened the above issue (https://github.com/jprichardson/node-fs-extra/issues/703) in fs-extra but the issue might lie in this project, I'm not sure.

Even after upgrading both packages I'm inconsistently getting the `cb.apply is not a function` error.

**Comment by isaacs** [comment]
@JustinLivi It's likely a result of having two different versions of `graceful-fs` in play at the same time.  What do you see when you run `npm ls graceful-fs`?

**Comment by JustinLivi** [comment]
@isaacs thanks - you were right. I was having a collision between jest and fs-extra. Installing graceful-fs as a direct dependency resolved the issue 👍
