### ISSUE TITLE
Tests for gfs global patch never actually tests local gfs

### ISSUE THREAD

**Issue by ZauberNerd** [isaacs/node-graceful-fs#163]
I noticed, that `node-tap` [has a dependency to `write-file-atomic`](https://github.com/tapjs/node-tap/blob/d5d3985142da6f40b9e64a884084cd364b8fb919/package.json#L56) which in turn [depends on `graceful-fs`](https://github.com/npm/write-file-atomic/blob/2191d03e97ecf447af30057d752b25fa07c1f32a/package.json#L24).

This is a problem when executing the test suite with the environment variable `TEST_GRACEFUL_FS_GLOBAL_PATCH` set, because then the `graceful-fs` from `node_modules` will already alter the `fs` module and therefore the `graceful-fs` implementation in this repository, that we actually want to test, will never be tested.

This blocks: https://github.com/isaacs/node-graceful-fs/pull/162

**Comment by isaacs** [comment]
write-file-atomic v3 will not include graceful-fs as a dependency, which should address this.
