### ISSUE TITLE
Error: ENOMEM: not enough memory

### ISSUE THREAD

**Issue by bi-kai** [isaacs/node-graceful-fs#168]
Error: ENOMEM: not enough memory, open '/starlab/www/newTest/OMStar_PS/3rdparty/lib/com.springsource.org.quartz-1.6.2.jar'
Emitted 'error' event at:
    at /starlab/www/automatic-upgrade-pkger/node_modules/graceful-fs/graceful-fs.js:190:14
    at /starlab/www/automatic-upgrade-pkger/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
  starlab:master worker9 is disconnect. +107ms
  starlab:master worker9 exited. +1ms
events.js:174
      throw er; // Unhandled 'error' event
      ^
![image](https://user-images.githubusercontent.com/15070379/62455450-ed971100-b7a8-11e9-8dd4-ded2e40a133e.png)
![image](https://user-images.githubusercontent.com/15070379/62455464-f7207900-b7a8-11e9-81e9-2b1094cfb19f.png)

All cluster workers quited, cause of this error, is it a problem of graceful itself?
My service is 16U32G, system resources are enough.

**Comment by coreyfarrell** [comment]
graceful-fs does not protect against memory exhaustion.  I believe you would see the same error if you removed graceful-fs.
