### ISSUE TITLE
How to use it in a React app?

### ISSUE THREAD

**Issue by hsluoyz** [isaacs/node-graceful-fs#180]
Does this module support front-end JS like React? Or Node.js only?

Should I use global patching way? Patching where?

**Comment by coreyfarrell** [comment]
`require('fs')` / `import fs from 'fs'` are not available in the browser so I don't see how this could be supported there.  I'd guess that you need to avoid it when targeting browsers or use some kind of build step to replace references to the `graceful-fs` module (and `fs` for that matter).  Likely works fine from Electron / NW.js.
