### ISSUE TITLE
Uncaught TypeError: fs$readFile is not a function in Webpack react app

### ISSUE THREAD

**Issue by anandkrishna93** [isaacs/node-graceful-fs#181]
Hi Team,

I am getting **"Uncaught TypeError: fs$readFile is not a function"** issue while running reactjs typescipt app with webpack,

**Uncaught TypeError: fs$readFile is not a function
    at go$readFile (graceful-fs.js:110)
    at Object.readFile (graceful-fs.js:107)
    at Object.readFileWithCallback (index.js:27)
    at Object.readFileWithCallback [as readFile] (index.js:5)**

and when I am running same with electron-webpack it is working fine, not giving any error.

Please tell me the solution or any alternate way.

**Comment by coreyfarrell** [comment]
It looks like somehow `require('fs')` was invalid.  The only way for this to happen with the current version is for `require('fs').readFile` to be undefined.  Does webpack replace `require('fs')` with something invalid?  Maybe something is using `require('graceful-fs').gracefulify(fs)` where `fs` is not valid.

Also please confirm that `npm ls graceful-fs` only lists 4.2.3.
