### ISSUE TITLE
Memory leak when loaded with different globals

### ISSUE THREAD

**Issue by SimenB** [isaacs/node-graceful-fs#183]
The current check looks for a `Symbol` (or a string on older nodes) on `global`, which fails when the module is evaluated in different contexts, like what Jest does.

I've put together a repository which is too small to really show the leak, but it illustrates what the issue is: https://github.com/SimenB/graceful-fs-jest-memleak

If we just log when `fs` is patched, this is the result:

![image](https://user-images.githubusercontent.com/1404810/77831926-7ac11880-7132-11ea-9531-48224f074b35.png)

If we add the queue to `fs` instead of `global`, this is the result:

![image](https://user-images.githubusercontent.com/1404810/77831935-90364280-7132-11ea-9793-75a5e0d81896.png)

**Comment by kirillgroshkov** [comment]
Cannot upvote enough!
