### ISSUE TITLE
pnpm silently fails with 0 exit code after update to graceful-fs 4.2.5

### ISSUE THREAD

**Issue by zkochan** [isaacs/node-graceful-fs#203]
I don't know how this is possible but after graceful-fs has been updated to 4.2.5, pnpm silently fails during installation. There is no error printed and the exit code is 0. Downgrading graceful-fs fixes the issue.

**Comment by GiladShoham** [comment]
Hi,
I'm the author of [bit](https://github.com/teambit/bit)
I have this issue too.
Since version 4.2.5 our app is completely broken in production.
The process exists with code 0 just in the middle of the installation process.

Please help us out here with a new patch version.
 
Thanks in advanced

**Comment by FeelyChau** [comment]
@zkochan @GiladShoham `copyFile` will miss the callback function if pass a flag, you can have a look at this: #202

**Comment by coreyfarrell** [comment]
4.2.6 has been released, should fix this issue.
