### ISSUE TITLE
Cannot be used in Worker threads (Node 10.x)

### ISSUE THREAD

**Issue by RomainMuller** [isaacs/node-graceful-fs#204]
The module cannot be loaded within a Worker thread, as `process.chdir` is not available (`undefined`) in there. The following line causes a `TypeError: Object prototype may only be an Object or null: undefined`:

https://github.com/isaacs/node-graceful-fs/blob/feedd03814a6fd4dbf3387c092fddde61dbab2bc/polyfills.js#L22

I reckon the solution would be to have `graceful-fs` also not provide `chdir` in this scenario.

**Comment by vijayshukla30** [comment]
When you going to release this fix getting error not able to even start the application.
<img width="1137" alt="Screenshot 2021-02-08 at 8 19 08 PM" src="https://user-images.githubusercontent.com/11537372/107235643-e9594d00-6a4a-11eb-975f-024bad45808b.png">

**Comment by coreyfarrell** [comment]
What version of node.js does this effect?  In my tests `typeof process.chdir === 'function'` from a worker thread.

**Comment by RomainMuller** [comment]
At least in `node 10`, as per https://nodejs.org/docs/latest-v10.x/api/process.html#process_process_chdir_directory:

> This feature is not available in Worker threads.

**Comment by mf-corey** [comment]
Thanks for the quick fix on this issue. I encountered it as well, it was preventing my Electron app from starting in node 10.20.1. The fix merged in this PR is the correct strategy, but I had luck launching my app with this small stop-gap that swallows the error... Use at your own risk.

```
var originalSetPrototypeOf = Object.setPrototypeOf;
Object.setPrototypeOf = function(a, b) {
  try {
    return originalSetPrototypeOf.apply(null, arguments);
  } catch (_error) {
    return console.error(_error);
  }
};
```
