### ISSUE TITLE
v4.2.8 and v4.2.7 break when used on node < 6

### ISSUE THREAD

**Issue by codeimpossible** [isaacs/node-graceful-fs#218]
When using graceful-fs v4.2.7+ `fs.readdir()` throws an exception on node < 6.

```
TypeError: callback must be a function
[20:31:16][Step 1/1]     at makeCallback (fs.js:78:11)
[20:31:16][Step 1/1]     at fs.readdir (fs.js:847:14)
[20:31:16][Step 1/1]     at go$readdir (node_modules\graceful-fs\graceful-fs.js:201:14)
[20:31:16][Step 1/1]     at Object.readdir (node_modules\graceful-fs\graceful-fs.js:198:12)
```

This is due to `options` being passed consistently in v4.2.7+ rather than before when it was only passed if it wasn't a function. `options` was added as part of fs.readdir() in node 6.0.0.

See [code before the change](https://github.com/isaacs/node-graceful-fs/blame/16f8da2f15e79288f12ab5acef87e94f99c1fe01/graceful-fs.js#L200) vs [code after the change](https://github.com/isaacs/node-graceful-fs/blob/master/graceful-fs.js#L201).

Could v4.2.7 and v4.2.8 be rolled back and shipped as breaking changes (v5.0.0) instead to prevent issues on older builds? Also, dropping node < 6 as a supported engine would be a good way to enforce any dependency on newer api signatures.

**Comment by pvw87** [comment]
I am having a similar issue using node v0.12.13. 
"graceful-fs" is one of the dependencies of "readdirp" package and its breaking the functionality. It was working fine with 4.2.6

**Comment by ZheyangSong** [comment]
Run into similar issue with `readdir` when using module `fs-extra`. As I far as I can track down the logic, the callback passed to `readdir` isn't called somehow.

**Comment by codeimpossible** [comment]
@isaacs just wondering if you've had a chance to look this over?

**Comment by isaacs** [comment]
Wow, running node 6 on a new mac is a _huge_ pita. 😅

I think this works now, please try with `npm install isaacs/node-graceful-fs` and if it fixes the issue, I'll publish to npm.
