### ISSUE TITLE
Problem with  webpack 4 : Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by mebest100** [isaacs/node-graceful-fs#222]
I build react on webpack 4.44.2, but when compile complete and it will report Object prototype may only be an Object or null: undefined from Browser console
as follow screenshot:
![image](https://user-images.githubusercontent.com/11530991/141315256-7ec25d3b-4be1-46bc-a935-3b09e46d094d.png)
![image](https://user-images.githubusercontent.com/11530991/141315403-2cb91923-230c-4d93-a237-c8dd270568b5.png)

It seems connected to graceful-fs, but I don't know how it come.
Could anybody told the root cause about the errors. Thx!

**Comment by atshweza** [comment]
I am also facing the same  issue @mebest100 any workarounds?
index.tsx:366 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at Function.setPrototypeOf (<anonymous>)
    at polyfills.js:139
    at patch (polyfills.js:141)
    at patch (graceful-fs.js:104)
    at Object.<anonymous> (graceful-fs.js:96)
    at Object../node_modules/node-localstorage/node_modules/graceful-fs/graceful-fs.js (graceful-fs.js:429)

**Comment by dargmuesli** [comment]
See #216.

**Comment by mebest100** [comment]
Yes, I solved this problem, the root cause comes from vscode, it insert
useless code and cause mentioned error.  Hence you just search by keywords
'from webpack' , and delete it when found, then everything is ok

Jonas Thelemann ***@***.***> 于 2021年12月5日周日 16:29写道：

**Comment by Cyrelc** [comment]
Having the same issue with Laravel-mix v 6 which has this as a dependency. I read 216 but am uncertain how to identify a package which "is attempting to run in the browser but should only run on node". Any help would be greatly appreciated

**Comment by Cyrelc** [comment]
Another message for the next person who finds this - I don't know why the issue pointed to graceful-fs but somebody - whether VSCode or mix or a misttype on my part that autocompleted - added an import to one of my files that was causing the issue

```import { find } from 'laravel-mix/src/File'```

**Comment by wangjia184** [comment]
I encountered the exactly same problem, the whole project can be found [here](https://github.com/wangjia184/monaco-svelte/tree/upgrade_version)

If I use the following version, everything is fine.
`"svelte-language-server": "^0.13.9"`

If I upgrade it,  gracefulFs fails with the exactly same error
`"svelte-language-server": "^0.14.0",`

**Comment by yoshixi** [comment]
I am facing same issue in my nuxt project. The nuxt mode is spa

**Comment by yoshixi** [comment]
version v4.2.5 or higher versions may cause this error
