### ISSUE TITLE
TypeError: Cannot read property 'uid' of undefined

### ISSUE THREAD

**Issue by washingtong33k** [isaacs/node-graceful-fs#224]
It seems like the issue reported in #88 is back with this new version 4.1.9.

Serverless uses graceful-fs as dependency, and since the latest release it's throwing this error. 

```
TypeError: Cannot read property 'uid' of undefined
      at Object.statSync (/usr/lib/node_modules/serverless/node_modules/graceful-fs/polyfills.js:313:17)
```

**Comment by RolKau** [comment]
@washingtong33k Maybe you must continue to upgrade to 4.2.9. https://github.com/isaacs/node-graceful-fs/commit/e61a20a052b838f420b98195c232a824a6ac04ee seems to fix the issue.

**Comment by washingtong33k** [comment]
@RolKau Thanks! This worked.
