### ISSUE TITLE
cb is not a function

### ISSUE THREAD

**Issue by vikas-shinde** [isaacs/node-graceful-fs#227]
Hi we are getting this error cb is not a function

internal/fs/streams.js:254
   cb(er || err);
   ^

TypeError: cb is not a function
   at internal/fs/streams.js:254:5
   at D:\MIndN\Bablr\Workspace\Final Testing\babygq\api\node_modules\graceful-fs\graceful-fs.js:61:14
   at FSReqCallback.oncomplete (fs.js:171:23)

we are using node version v14.15.0
can any one help us to resolve this problem.

**Comment by kylet91** [comment]
Same issue here, this blog post fixed it for me: https://flaviocopes.com/cb-apply-not-a-function/

**Comment by isaacs** [comment]
This was fixed in graceful-fs v4.2.9.  Please update.

**Comment by vikas-shinde** [comment]
We are using let us version v4.2.9 but still giving error cb is not a function

**Comment by vikas-shinde** [comment]
We manage to fixes this problem. we just modify the file graceful-fs.js at location node_modules\graceful-fs\graceful-fs.js

for aver environment it gives error at line 61:14 that is this line 

if (typeof cb === 'function')
          cb.apply(this, arguments)

we just add this line in to try and catch block and its work for me

**Comment by isaacs** [comment]
Yeah, cb is definitely a function there.

To debug this, I'll need _at minimum_ the actual stack trace (with line number) and the output of `npm ls graceful-fs` (to see the version you're using).  The line you're showing, in the latest released version, is definitely ensuring that `cb` is a function prior to calling it.  So it's not that.
