### ISSUE TITLE
Manipulate PDF with NUXT 3 for digital sign

### ISSUE THREAD

**Issue by hermesalvesbr** [isaacs/node-graceful-fs#228]
Hi there,

I'm trying to sign a pdf file with a certificate p12(pfx file), but my error is about FS with NUXT3

![159770433-9063e9d3-ccc8-4552-9a86-afc89bad054d](https://user-images.githubusercontent.com/379850/159818005-8aa3ffe2-d697-4a89-b59b-fade18eaa777.png)

I need to make a special configuration for work with nuxt 3? 

Thanks for any response!

**Comment by isaacs** [comment]
This module is not intended to be used in web browsers, only in Node.js on the server.  It looks like there's no `platform` object.
