### ISSUE TITLE
silent failure when attempting to write too many files

### ISSUE THREAD

**Issue by jlukanta** [isaacs/node-graceful-fs#32]
@fresheneesz reported this bug at https://github.com/joyent/node/issues/8399

He has the following test program:

    var stream = require('stream')
    var fs = require("graceful-fs")
    
    for(var x=0; x<10000; x++) {
        var filename = __dirname+'/x/'+x
        var s = new stream.PassThrough()
        s.write("moo"+x)
        fs.createWriteStream(filename, s)
    }

This program writes files in the x directory up until 1014, after which the program simply exits with no error at all, but there is no file created for 1015 and above. He's on node v0.10.25, centos 6.5.

**Comment by isaacs** [comment]
That's not the way to write to a file stream. You're never closing or ending these files, so it can never know that it's ok to retry the failed opens. Check out the stream test on master. Dont create a passthrough at all. Just write to the write stream, and call end when you're done.
