### ISSUE TITLE
Running `fs` source fails if it requires internal modules

### ISSUE THREAD

**Issue by vkurchatkin** [isaacs/node-graceful-fs#41]
https://github.com/nodejs/io.js/issues/1898

**Comment by Fishrock123** [comment]
As stated [here](https://github.com/nodejs/io.js/issues/1898#issuecomment-109259158) the problem appears to be https://github.com/isaacs/node-graceful-fs/blob/master/fs.js#L8-L10 (i.e. running `process.binding('natives').MODULE` though eval.)

**Comment by Fishrock123** [comment]
Related to #33 and 34e473a915b6d10379151ce3b8ce591549b35c8a / (it's revert) 5eb4fee3c0c2905e19c7ca675a662072f2cd639e
