### ISSUE TITLE
graceful-fs does not work properly with io.js

### ISSUE THREAD

**Issue by bpasero** [isaacs/node-graceful-fs#43]
When using fs functions like readFile(), graceful-fs is not in the loop when running with io.js. To reproduce:

```javascript
var gfs = require("graceful-fs");

gfs.readFile('package.json', function(err, res) {
 	console.log(res.toString());
 });
```

and the package.json:

```json
{
	"name": "name",
	"description": "description",
	"author": "author",
	"version": "1.0.0",
	"main": "pathToMain",
	"dependencies": {
		"graceful-fs": "*"
	}
}
```

I added a console.log() statement into graceful-fs to make sure its hit:

```javascript
Req.prototype.done = function (er, result) {
  console.log("DONE: ", er, result);
```

When running with node.js, the output shows up, but not with io.js. 

According to https://github.com/atom/electron/issues/1903#issuecomment-110232253 this is caused by io.js now calling binding.open() and no longer fs.open() for readFile.

**Comment by Fishrock123** [comment]
The aforementioned code linked to by electron originates in this commit: https://github.com/nodejs/io.js/commit/e65308053c871352be948b9001737df01aad1965#diff-9a205ef7ee967ee32efee02e58b3482dR242

The technical problem is this: https://github.com/isaacs/node-graceful-fs/blob/master/fs.js#L8-L10

Using `process.binding()` (especially in this way) effectively voids the warranty. Perhaps there is some other way to wrap / patch `fs`?

If not, I think I've motioned before that I wouldn't mind this functionality being in core. See also, this twitter thread: https://twitter.com/isntitvacant/status/608708444539895809

**Comment by vkurchatkin** [comment]
`node-graceful-fs` relies on implementation details heavily. Either we should include it in core or rewrite it using public API only.

**Comment by bpasero** [comment]
+1 for making this part of io.js and/or the future node. The fact that this lib has to go deep into internals shows that it belongs into core. I would not even make it optional or through a flag. If I hit EMFILE, just retry for up to N times.

**Comment by Fishrock123** [comment]
See also: https://github.com/nodejs/io.js/issues/1941

**Comment by Fishrock123** [comment]
> +1 for making this part of io.js and/or the future node. The fact that this lib has to go deep into internals shows that it belongs into core.

Yes, I think you make a good point here. Stuff that can't be otherwise properly supported is what ought to be the primary candidates for core APIs.

**Comment by isaacs** [comment]
Fixed on v4
