### ISSUE TITLE
Deprecate all versions prior to 4.x

### ISSUE THREAD

**Issue by ChALkeR** [isaacs/node-graceful-fs#58]
Users should be warned that their setups will we soon broken with new Node.js releases.

This means to push a patch release to 1.x, 2.x, and 3.x branches.
Something similar to what `lodash` does:
```
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
```

Tracking issue: https://github.com/nodejs/node/issues/5213

**Comment by ChALkeR** [comment]
Proposed solution:
add 
```json
  "deprecated": "graceful-fs<4.0.0 is deprecated and will be broken on newer Node.js versions. Upgrade to graceful-fs@^4.0.0 or later.",
```
to `package.json` of v2.1.0 and v3.0.8 and publish those as v2.1.1 and v3.0.9.

/cc @isaacs

**Comment by isaacs** [comment]
Thanks for the suggestion.  I'll do this when I get to a computer. 

Just so you know, and for posterity, editing package.json and publishing a new version is not the best way to deprecate a package. Deprecation should be done using the `npm deprecate` command.

**Comment by ChALkeR** [comment]
@isaacs Ah, I wasn't aware that it is possible to that way, thanks!

**Comment by isaacs** [comment]
Done.

```
npm deprecate "graceful-fs@<4.0.0" "graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible."
```

**Comment by ChALkeR** [comment]
Thanks!
