### ISSUE TITLE
cannot install version 4

### ISSUE THREAD

**Issue by Horiatu** [isaacs/node-graceful-fs#59]
Whatever I do, I end up with version 3.3.12!

This is my package:
[package.zip](https://github.com/isaacs/node-graceful-fs/files/133370/package.zip)
and I'm running 'npm install' from the folder containing this package.
When running 'npn -v graceful-fs' I'm getting 3.3.12

Please help: what am I doing wrong?

**Comment by isaacs** [comment]
That zip file contains the package.json for graceful-fs.  What's in the package.json for your project?

**Comment by isaacs** [comment]
Maybe try this?  `npm install graceful-fs@latest --save` to install the latest and also save it to your project's package.json file.

**Comment by Horiatu** [comment]
tx issacs,

I tried that, at first I thought it was working, but this is what I got:

F:\polymer-starter-kit-1.2.3>npm install graceful-fs@latest --save
F:\polymer-starter-kit-1.2.3
└── graceful-fs@4.1.3


F:\polymer-starter-kit-1.2.3>npm -v graceful-fs
3.3.12

This is the package from the starter kit:
[package.zip](https://github.com/isaacs/node-graceful-fs/files/134469/package.zip)

It does not work for plenty of errors, but the first reported error is the version of graceful-fs.
(I'm new to npm, I just wanted to install the starter-kit and go on with polymer, but seems that is not so easy...)

**Comment by isaacs** [comment]
HAHah, omg, I'm so sorry, I should've caught this.

`npm -v` is a shorthand for `npm --version`.  It prints the *npm* version when you do that, and ignores all other arguments.

I think what you're looking for is maybe `npm ls graceful-fs`.

**Comment by isaacs** [comment]
By the way, I'm laughing at myself, not at you.  I should know how npm works, sorry, I'm feeling a little bit embarrassed.

**Comment by Horiatu** [comment]
No hard feeling. In fact thanks!

Still running the starter kit package I'm getting errors - lot of them - starting like this:

F:\polymer-starter-kit-1.2.3>npm ls graceful-fs
F:\polymer-starter-kit-1.2.3
└── graceful-fs@4.1.3

F:\polymer-starter-kit-1.2.3>npm install
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fai
l on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possibl
e.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fai
l on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possibl
e.
...

I have no clue what's wrong and how to continue...
