### ISSUE TITLE
Upgrading from v3 to v4

### ISSUE THREAD

**Issue by jacksonrayhamilton** [isaacs/node-graceful-fs#60]
Hi, could you explain the breaking changes (if any) that I may incur by upgrading this package from `v3.x` to `v4.x`?

**Comment by Xuff** [comment]
Yes, or provide a proper change log.

**Comment by jacksonrayhamilton** [comment]
Ah yes, we already have #51 for that.

**Comment by isaacs** [comment]
There is a changelog in the readme.
