### ISSUE TITLE
npm WARN deprecated message a bit unclear

### ISSUE THREAD

**Issue by sterpe** [isaacs/node-graceful-fs#61]
```
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
```

Hi @isaacs, does it feel like this message could be improved by specifying which 'newer node releases' will be broken?  Is it broken for node 4 LTS or 5 or both?

Thanks

**Comment by popomore** [comment]
It will break in node6

**Comment by isaacs** [comment]
Updated.

> npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible.

**Comment by ChALkeR** [comment]
No, it's not. It's going to break in Node.js 7.0.
