### ISSUE TITLE
Update deprecation warning s/6/7/

### ISSUE THREAD

**Issue by ChALkeR** [isaacs/node-graceful-fs#64]
See https://github.com/isaacs/node-graceful-fs/issues/61#issuecomment-215514206 — that message is not correct.

Only a runtime warning landed in Node.js 6.0, that warning will be turned into a throw in Node.js 7.0.

Refs: nodejs/node#6413, nodejs/node#5213, nodejs/node#5102.

**Comment by ChALkeR** [comment]
The initial graceful-fs deprecation message was fine, but it was mistakenly changed in #61.

**Comment by isaacs** [comment]
Aha!  Sorry for my confusion.  Updated deprecation warning.  Thanks for the update.

**Comment by ChALkeR** [comment]
@isaacs Thanks!
