### ISSUE TITLE
LTS Node 6.0: re-evaluating native module sources is not supported

### ISSUE THREAD

**Issue by denji** [isaacs/node-graceful-fs#66]
Unstable behavior in the stable version of node
---
```bash
$ node --version
v6.0.0
$ gulp
(node:57017) fs: re-evaluating native module sources is not supported.
If you are using the graceful-fs module, please update it to a more recent version.
```

**Comment by isaacs** [comment]
Node 6.0.0 is not LTS, and this issue is already addressed on the latest graceful-fs.

The older version of graceful-fs already has a deprecation warning asking you to upgrade to a newer version.

Use `npm ls graceful-fs` to find out where in the dependency tree it lives, and what needs to be updated.

**Comment by paulcpederson** [comment]
@isaacs I get this error on a fresh install of the most recent graceful-fs:

```
$ node --version
v6.5.0
$ npm install graceful-fs
(node:60456) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
test
└── graceful-fs@4.1.6
```

Is this because I'm using 6.5.0?

**Comment by isaacs** [comment]
@paulcpederson You'd only get that when _running_ graceful-fs of version 3 less than 3.10, not merely installing it.

What version of npm are you running?  You could do `npm -v` to find out.

You can also type `npm ls graceful-fs` in your codebase to find this.  It looks like it's happening in the npm command itself, so you could do `npm explore npm -g -- npm ls graceful-fs` to see what versions of graceful-fs might be loaded by the npm program.

**Comment by denji** [comment]
```bash
 ~  npm explore npm -g -- npm ls graceful-fs
npm@2.15.9 /usr/local/lib/node_modules/npm
└── graceful-fs@4.1.4
 ~  node --version
v6.5.0
 ~  npm --version
3.10.3
 ~  n --lts
4.5.0
 ~  n --latest
6.5.0
```

**Comment by paulcpederson** [comment]
@isaacs you were right! IT was npm itself. Upgraded and now it's not a problem. Thanks!
