### ISSUE TITLE
support node v6.0

### ISSUE THREAD

**Issue by lv7777** [isaacs/node-graceful-fs#67]
when I compiled using debowerify,I get follow message.

```
(node:6292) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```
fortunately,I using nvm,so I switched simply,but supporting wide range is important.

**Comment by lv7777** [comment]
sorry.
maybe occurred by bowerify.
this package was not related.

see https://github.com/eugeneware/debowerify/issues/83

**Comment by psypersky** [comment]
+1

**Comment by lv7777** [comment]
closed.
