### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by sethmurphy18** [isaacs/node-graceful-fs#70]
So, I have looked into this issue as much as I possibly can, and I cannot trace the source of this issue to anywhere, but here. When I run my app in Google Chrome (version 51.0.2704.106) and Microsoft Edge (version 38.14372.0.0), I get an error on the console that stops all script execution:
```
Uncaught TypeError: Cannot read property 'prototype' of undefined
```

The issue seems to be thrown on line 157 of the script...I am not too sure what is causing it...

I have tried Node version 6.3.0 and version 4.4.7, both using the 64-bit version. I have completely deleted my node_modules and installed them from scratch, and the error still persists. The worst part is that it was working previously, then stopped.

**Comment by eric-burel** [comment]
Same issue here with 6.3.0, it prevents me from installing some package that rely upon graceful-fs. I am trying to work out a solution.

**Comment by sethmurphy18** [comment]
My workaround sadly was to go back to ASP.NET MVC.

**Comment by sethmurphy18** [comment]
A suggestion however to be more Meteor friendly would be to use ES6 exports...sadly, that would mean losing compatibility with versions < 1.3.

**Comment by SilverDFlame** [comment]
Looking further into the issue, because I'm also not able to install `graceful-fs`, it's a new dependency written by IsaacS, that npm isn't seeing right.

```
13:46:35 npm sill addNameRange number 2 { name: 'natives', range: '>=1.0.1 <2.0.0', hasData: true }
13:46:35 npm sill addNameRange versions [ 'natives', [] ]
13:46:35 npm verb stack TypeError: Cannot read property 'latest' of undefined
13:46:35 npm verb stack     at next (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/lib/cache/add-named.js:248:35)
13:46:35 npm verb stack     at setData (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/lib/cache/add-named.js:236:5)
13:46:35 npm verb stack     at RES (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
13:46:35 npm verb stack     at f (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/once/once.js:17:25)
13:46:35 npm verb stack     at fixName (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/lib/cache/add-named.js:29:5)
13:46:35 npm verb stack     at saved (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/lib/cache/caching-client.js:173:7)
13:46:35 npm verb stack     at /opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
13:46:35 npm verb stack     at FSReqWrap.oncomplete (fs.js:82:15)
13:46:35 npm verb cwd /var/lib/jenkins/jobs/guest-connect-v1-build/workspace/public
13:46:35 npm ERR! Linux 4.1.10-17.31.amzn1.x86_64
13:46:35 npm ERR! argv "/opt/nodejs/node-v4.4.3-linux-x64/bin/node" "/opt/nodejs/node-v4.4.3-linux-x64/bin/npm" "install" "--loglevel" "silly"
13:46:35 npm ERR! node v4.4.3
13:46:35 npm ERR! npm  v2.15.1
13:46:35 
13:46:35 npm ERR! Cannot read property 'latest' of undefined
13:46:35 npm ERR! 
13:46:35 npm ERR! If you need help, you may report this error at:
13:46:35 npm ERR!     <https://github.com/npm/npm/issues>
```

Notice on the second line, where it's talking about versions, the array of versions is empty. This is why the install is failing.

**Comment by isaacs** [comment]
@SilverDFlame That's interesting, but not at all related to the OP in this thread.  Can you please post a new issue?  Thanks.

**Comment by Galileo1** [comment]
Hey peeps,

I am getting the same error on line - 
var fs$ReadStream = fs.ReadStream
ReadStream.prototype = Object.create(fs$ReadStream.prototype)

Were you guys able to solve this ?
node version 6.2.2

Cheers

**Comment by sethmurphy18** [comment]
Sadly no, I have not been able to resolve it. I believe the issue is tied to how Meteor handles Node imports in my case. There is probably something in the package itself I am missing, but I haven't really investigated the source code to be sure. At this point, I'm just chalking it up to how @meteor handles Node imports and ES6.

**Comment by isaacs** [comment]
It doesn't sound like this is a Meteor issue, and thus not a thing that graceful-fs can fix.
