### ISSUE TITLE
TypeError: Cannot read property 'uid' of undefined

### ISSUE THREAD

**Issue by rmwxiong** [isaacs/node-graceful-fs#88]
Just started appearing with 4.1.7 for me. I'm running a karma test, but haven't yet identified what is using graceful-fs

**Comment by mordocai** [comment]
I am getting:

    Fatal error: Cannot read property 'uid' of undefined
    graceful-fs/polyfills.js:264
    if (stats.uid < 0) stats.uid += 0x100000000

For me karma is using graceful-fs

**Comment by MrRoyce** [comment]
I just did an npm install, this is breaking the build with:

.../node_modules/graceful-fs/polyfills.js:264
      if (stats.uid < 0) stats.uid += 0x100000000

TypeError: Cannot read property 'uid' of undefined
    at .../node_modules/graceful-fs/polyfills.js:264:16
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by pkat** [comment]
Same thing started happening for me. Breaking our app build: 
```
..node_modules/less/node_modules/graceful-fs/polyfills.js:264
      if (stats.uid < 0) stats.uid += 0x100000000
               ^

TypeError: Cannot read property 'uid' of undefined
    at ..node_modules/less/node_modules/graceful-fs/polyfills.js:264:16
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by rmwxiong** [comment]
@isaacs fyi

**Comment by addaleax** [comment]
yeah, sorry, this is obviously my bad. I’ll have a patch ready in a few seconds.

**Comment by 4ossiblellc** [comment]
It is happening to me as well

**Comment by awkaiser** [comment]
Just adding to the 🔥  here. Seeing this as well, and it sent me into quite the panic!

**Comment by 4ossiblellc** [comment]
![dgvdxcp](https://cloud.githubusercontent.com/assets/13743621/18853734/ae1d1b84-83fb-11e6-936e-b86026669f46.gif)

**Comment by kflorence** [comment]
Nobody's perfect, thanks for the quick fix.

**Comment by isaacs** [comment]
Sorry, everyone.  I should've caught that.  Maybe there should be a test suite that just does a bunch of fs stuff and verifies that nothing throws any errors...

**Comment by mikegwhit** [comment]
Still getting this , 5.2.2 and 5.3.0 and testing 5.1.2 will report back..

OK: Resolving.. but for anyone looking to reopen, see if:
* you are trying to drop privileges from root pm2 call..
* pm2 seems to communicate by reading files in your ~/.pm2 dir
* you need to change the access on this dir to be read by other users..
* this probably has a constraint you also shouldn't run any actual sudo processes via pm2 without dropping privileges
