### ISSUE TITLE
Bug: access to stats object is not guarded

### ISSUE THREAD

**Issue by normanrz** [isaacs/node-graceful-fs#90]
In the recently introduced commit https://github.com/isaacs/node-graceful-fs/commit/f5287299ae67d490531b7e6ce57fd448d28d2a70#diff-97c39d3af7596745c8b20ad3a591d4dc the stats object is accessed before it is checked. However, if there is an error the stats variable will be undefined leading to a `TypeError`.

**Comment by mordocai** [comment]
Duplicate of number #88 though more exact

**Comment by normanrz** [comment]
Alright, seems like I was a couple of minutes too late ;-)
