### ISSUE TITLE
has 4.18 been published yet? 

### ISSUE THREAD

**Issue by michaelwarren1106** [isaacs/node-graceful-fs#94]
trying to get rid of the "cannot find uid" errors, but npm wont seem to install #4.1.8

**Comment by isaacs** [comment]
Yep, it's there.

```
$ npm view graceful-fs version
4.1.8
```

https://www.dropbox.com/s/zivm4kwwqhbnisf/Screenshot%202016-09-27%2013.55.35.png?dl=0

http://registry.npmjs.org/graceful-fs

**Comment by isaacs** [comment]
Possibly you're depending on version 4.1.7 explicitly or something?

**Comment by michaelwarren1106** [comment]
i was trying to explicitly install 4.1.8 and getting errors

```shell
npm ERR! argv "/prod/msp/domains/node-v4.3.1-linux-x64/bin/node" "/prod/msp/domains/node/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v3.7.3

npm ERR! No compatible version found: graceful-fs@4.1.8
npm ERR! Valid install targets:
npm ERR! 4.1.7, 4.1.6, 4.1.5, 4.1.4, 4.1.3, 4.1.2, 4.1.1, 4.1.0, 3.0.11, 3.0.10, 3.0.9, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.14, 1.1.13, 1.1.12, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /prod/msp/build/slave2/workspace/OneUI/mercury-build/mercury-ui/npm-debug.log
 ���
Build step 'Execute shell' marked build as failure
```

**Comment by michaelwarren1106** [comment]
```
+ node -v
v4.3.1
+ npm view graceful-fs version
4.1.7
```

**Comment by michaelwarren1106** [comment]
does it take some time to propagate across npmjs servers or something? some sort of sync issue that needs a while to resolve?

**Comment by isaacs** [comment]
Are you behind a proxy, or perhaps some kind of cache that has to be updated?

Everthing's green on this side.

**Comment by michaelwarren1106** [comment]
yeah, I'm all good now. I am behind a proxy, and I think i ran into the default registry problem. I have a feeling that our Jenkins boxes are pointed to an installation of nexus or something that's not the main registry, because when I added an .npmrc to my project with a registry entry pointing to npmjs.irg, 4.1.8 came up just fine...thanks for the help!
