### ISSUE TITLE
Bump to v4.1.9 broke our test suite

### ISSUE THREAD

**Issue by dannyphillips** [isaacs/node-graceful-fs#95]
After upgrading to 4.1.9, our mocha tests fail and gives the following output:

```
/home/ubuntu/wrench/node_modules/bluebird/js/release/debuggability.js:673
    var firstStackLines = firstLineError.stack.split("\n");
                                        ^
NetworkError: 
npm ERR! Test failed.  See above for more details.

npm test returned exit code 1
```

**Comment by dannyphillips** [comment]
Locking to v4.1.8 seems to resolve the issue

**Comment by isaacs** [comment]
@dannyphillips That's really strange.  Is there a reproducible test I can check out?

**Comment by isaacs** [comment]
Closing because I cannot reproduce.  This error is obscured by Bluebird, and I can't get at the cause without reproducing it locally to dig in.
